# Note that this needs VAULT_ADDR and VAULT_TOKEN environment variables to be set
- name: Configure vault
  hosts: localhost-py3
  gather_facts: no
  tasks:
  - name: enables secret backend
    hashivault_secret_engine:
      backend: kv
      description: General store for various pieces of data
      name: secret
      state: present
      options:
        version: 2
  - name: enable userpass login
    hashivault_auth_method:
      method_type: userpass
      state: enabled
  - name: enable AppRole login
    hashivault_auth_method:
      method_type: approle
      state: enabled
  - name: create a test user
    hashivault_userpass:
      name: testuser
      pass: testpass
      policies: test_policy
    no_log: true
  - name: create policies
    hashivault_policy_set:
      name: "{{item | basename}}"
      rules: "{{lookup('file', item)}}"
    with_fileglob:
    - "policies/*"
