- hosts: postgres
  gather_facts: no
  vars:
    login_user: postgres
    login_password: notapass
    vault_db_user: vault
    vault_db: vault
    vault_db_password: vaultdbpass
    kv_table: vault_kv_store
    ha_table: vault_ha_locks
  tasks:
  - name: create database for vault
    postgresql_db:
      name: '{{vault_db}}'
      login_host: '{{ansible_host}}'
      login_password: '{{login_password}}'
      state: present
    delegate_to: 127.0.0.1
  - name: create storage table for vault
    postgresql_table:
      name: '{{kv_table}}'
      login_host: '{{ansible_host}}'
      login_password: '{{login_password}}'
      state: present
      db: '{{vault_db}}'
      columns:
      - parent_path TEXT COLLATE "C" NOT NULL
      - path        TEXT COLLATE "C"
      - key         TEXT COLLATE "C"
      - value       BYTEA
      - CONSTRAINT pkey PRIMARY KEY (path, key)
    delegate_to: 127.0.0.1
  - name: create index on storage table
    postgresql_idx:
      name: parent_path_idx
      login_host: '{{ansible_host}}'
      login_password: '{{login_password}}'
      state: present
      db: '{{vault_db}}'
      table: '{{kv_table}}'
      columns: parent_path
    delegate_to: 127.0.0.1
  - name: create HA table for vault
    postgresql_table:
      name: '{{ha_table}}'
      login_host: '{{ansible_host}}'
      login_password: '{{login_password}}'
      state: present
      db: '{{vault_db}}'
      columns:
      - ha_key      TEXT COLLATE "C" NOT NULL PRIMARY KEY
      - ha_identity TEXT COLLATE "C" NOT NULL
      - ha_value    TEXT COLLATE "C"
      - valid_until TIMESTAMP WITH TIME ZONE NOT NULL
    delegate_to: 127.0.0.1
  - name: create user for vault
    postgresql_user:
      name: '{{vault_db_user}}'
      db: '{{vault_db}}'
      login_host: '{{ansible_host}}'
      login_password: '{{login_password}}'
      password: '{{vault_db_password}}'
      encrypted: yes
      state: present
      priv: CONNECT/{{kv_table}}:ALL/{{ha_table}}:ALL
    delegate_to: 127.0.0.1
